### PR TITLE
fixes #60; commissions-search work

### LINKED ISSUE #60: Updates/fixes to search page
- [x] add a little more space between filter options so the separation between "Policy Area" and "Open Seats" sections on mobile and desktop is clearer
- [x] make filter drawer automatically close when "Apply" is hit on mobile
- [x] pressing enter on search doesn't do anything. This was fixed last week on the testing instance (https://boston-gov-commissions-search.digital-staging.boston.gov/commissions-search) but seems to be broken again
- [x] it looks like the search page is pulling from the dev database on the testing instance since its not using updated URLs. This was also fixed/working last week

### PR DESCRIPTION
**Pull request by jessicamarcus**
Did a pass at some React refactoring/cleanup, and extracted the radio button into the pattern library. Realized the app form commissions list alphabetization got lost somewhere, so fixed that as well.

### CODE REVIEW

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
+import React from 'react';
+
+
+interface RadioProps {
+  name: string;
+  labelText: string;
```
Comment (fionawhim) [inline modules-js/react-fleet/src/form-elements/inputs/Radio.tsx]: Is there a reason this is `labelText` and not `label`?

Also, it would be good to change this to `ReactNode` so that you can put markup in there as well as plain strings.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+      <span className="ra-l">{props.labelText}</span>
+    </label>
+  );
+}
+
+
+interface RadioItem {
+  labelText: string;
+  value?: string;
+  checked?: boolean;
```
Comment (fionawhim) [inline modules-js/react-fleet/src/form-elements/inputs/Radio.tsx:55]: It might be neat rather than passing this as a boolean but put a `checkedValue` on the `RadioGroupProps` and automatically `checked` the right child based on that.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+}
+
+/**
+ * Render a collection of radio buttons by providing an array of radio item information objects.
+ */
+export function RadioGroup(props: RadioGroupProps): JSX.Element {
+  return (
+    <div
+      role="group"
+      aria-label={props.groupLabel || props.name}
```
Comment (fionawhim) [inline modules-js/react-fleet/src/form-elements/inputs/Radio.tsx]: The code I'm working on now could def. use this component. Could you add rendering the label as a div with `txt-l` on it? I'm not sure how that should interact w/ `aria-label` tho.

Alternately I can make that change in my PR, though I’ll still ask for your help w/ ARIA.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+    >
+      {props.items.map((item, index) => (
+        <Radio
+          key={`radio-${index}`}
+          name={props.name}
+          labelText={item.labelText}
+          value={item.value}
+          checked={item.checked}
+          onChange={props.handleChange}
+          className="p-b200"
```
Comment (fionawhim) [inline modules-js/react-fleet/src/form-elements/inputs/Radio.tsx]: `onBlur`?

File: services-js/commissions-search/src/App.js [hunk 5]
```diff
@@ -1,113 +1,112 @@
...
+    };
+
+  }
 
   handleCheckChange = event => {
     const target = event.target;
     const checked = target.checked;
     const name = target.name; //area id
 
+    let currentAreas = null;
```
Comment (fionawhim) [inline services-js/commissions-search/src/App.js]: could leave off the `= null` since it will be assigned in both codepaths.

File: services-js/commissions-search/src/App.js [hunk 6]
```diff
@@ -1,113 +1,112 @@
...
+    this.setState({ currentSeats: event.target.value });
   };
 
   handleFacetSubmit = event => {
     event.preventDefault();
+
     this.setState({
       submittedAreas: this.state.currentAreas,
-      submittedSeats: this.state.currentSeats,
+      submittedSeats: this.state.currentSeats
```
Comment (fionawhim) [inline services-js/commissions-search/src/App.js:61]: Hrm. Prettier should have put a trailing comma here…

File: services-js/commissions-search/src/App.js [hunk 7]
```diff
@@ -1,113 +1,112 @@
...
     });
   };
 
   handleKeywordChange = event => {
-    this.setState({
-      currentKeywords: event.target.value,
-    });
+    this.setState({ currentKeywords: event.target.value, });
```
Comment (fionawhim) [inline services-js/commissions-search/src/App.js:66]: and removed this trailing comma

File: services-js/commissions-search/src/FacetList.js [hunk 8]
```diff
@@ -14,47 +17,63 @@ const GET_AREAS = gql`
...
-            checked={props.checked}
-            onChange={props.handleCheckChange}
-          />
-          <span className="cb-l">{props.name}</span>
-        </label>
-      );
-    }
+function returnArea(props, policy_area) {
+  // to conserve horizontal space, convert "and" to an ampersand; Oxford comma
+  // looks odd in this case, and the Chicago Manual of Style agrees - jm
```
Comment (fionawhim) [inline services-js/commissions-search/src/FacetList.js:22]: 👍

File: services-js/commissions-search/src/FacetList.js [hunk 9]
```diff
@@ -14,47 +17,63 @@ const GET_AREAS = gql`
...
-            value={props.id}
-            className="cb-f"
-            checked={props.checked}
-            onChange={props.handleCheckChange}
-          />
-          <span className="cb-l">{props.name}</span>
-        </label>
-      );
-    }
+function returnArea(props, policy_area) {
```
Comment (fionawhim) [inline services-js/commissions-search/src/FacetList.js]: camel case `policyArea`

Also I don’t understand this function name. Maybe `renderArea` or `renderAreaCheckbox`?

File: services-js/commissions-search/src/FacetList.js [hunk 10]
```diff
@@ -14,47 +17,63 @@ const GET_AREAS = gql`
...
+  // to conserve horizontal space, convert "and" to an ampersand; Oxford comma
+  // looks odd in this case, and the Chicago Manual of Style agrees - jm
+  const labelText = policy_area.name.replace(/(and|, and)/, '&');
```
Comment (fionawhim) [inline services-js/commissions-search/src/FacetList.js]: Doesn’t this remove the space in the Oxford comma situation? "A, and B" -> "A& B"

File: services-js/commissions-search/src/FacetList.js [hunk 11]
```diff
@@ -14,47 +17,63 @@ const GET_AREAS = gql`
...
+
+    this.filterVisibilityRef = React.createRef();
+  }
+
+  handleSubmit = e => {
+    this.props.handleFacetSubmit(e);
+
+    // If visible, close drawer after applying filters;
+    // this is only relevant with narrow/mobile viewports.
+    this.filterVisibilityRef.current.checked = false;
```
Comment (fionawhim) [inline services-js/commissions-search/src/FacetList.js:54]: 👍

File: services-js/commissions-search/src/ResultList.js [hunk 12]
```diff
@@ -1,128 +1,100 @@
...
-              <div className="n-li-t g--8">{props.name}</div>
-              <div className="n-li-ty n-li-ty--r g--44">
-                {props.policyName.name}
-              </div>
-            </a>
-          </li>
-        );
-      }
-    }
+  returnResult = ({ id, name, policyType, homepageUrl }) => {
```
Comment (fionawhim) [inline services-js/commissions-search/src/ResultList.js]: I think “return” in function names may be redundant. `renderCommissionItem` or `renderCommissionRow`?

File: services-js/commissions-search/src/ResultList.js [hunk 13]
```diff
@@ -1,128 +1,100 @@
...
+
+          } else {
             return (
               <div className="b-c b-c--mh">
                 <h2 className="h2 m-t000 m-b300">No Results Found</h2>
+
                 <div className="intro-text supporting-text lh--200">
-                  Thomas Paine noted "These are the times that try men's souls."
-                  Well this is a time to try another search.
+                  <p>Thomas Paine noted <q style={{ fontStyle: 'italic' }}>These are the times that try men’s souls.</q></p>
```
Comment (fionawhim) [inline services-js/commissions-search/src/ResultList.js:81]: got that semantic html

**Review by fionawhim — COMMENTED** [review]
Solid cleanup.

Just a few things.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx (hunk 1 above)
Comment (jessicamarcus) [reply modules-js/react-fleet/src/form-elements/inputs/Radio.tsx]: That's a great idea. I felt that `labelText` was more descriptive, but if markup will also be allowed, `label` is definitely more appropriate.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx (hunk 3 above)
Comment (jessicamarcus) [reply modules-js/react-fleet/src/form-elements/inputs/Radio.tsx]: On it - I'll add in an option to visually hide the label, similar to what I've done with my TextInput. The component will add an `aria-label` or `aria-labelledby` attribute, depending on that visibility.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx (hunk 4 above)
Comment (jessicamarcus) [reply modules-js/react-fleet/src/form-elements/inputs/Radio.tsx]: We might want to use this element with a handler for that event in the future.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx (hunk 2 above)
Comment (jessicamarcus) [reply modules-js/react-fleet/src/form-elements/inputs/Radio.tsx:55]: I like that. 😄

File: services-js/commissions-search/src/FacetList.js (hunk 10 above)
Comment (jessicamarcus) [reply services-js/commissions-search/src/FacetList.js]: oops - you're so right.

File: modules-js/react-fleet/src/form-elements/inputs/Radio.tsx [hunk 14]
```diff
@@ -27,50 +31,75 @@ export default function Radio(props: RadioProps): JSX.Element {
...
+ *
+ * Group label must be included; if it should be visually hidden, its text is
+ * added as an aria-label.
+ *
+ * If checked value is coming from a parent, pass it in as "checkedValue" prop.
  */
 export function RadioGroup(props: RadioGroupProps): JSX.Element {
+  const ariaProps = {};
+
+  props.hideLabel ? ariaProps['aria-label'] = props.groupLabel : ariaProps['aria-labelledby'] = `${props.name}-groupLabel`;
```
Comment (fionawhim) [inline modules-js/react-fleet/src/form-elements/inputs/Radio.tsx:83]: This should be an `if`/`else` statement. Save the ternary operator for when you need to return a value. (Such as `const foo = flag ? 'a' : 'b'`)

File: services-js/commissions-search/src/FacetList.js [hunk 15]
```diff
@@ -17,15 +17,15 @@ const GET_AREAS = gql`
   }
 `;
 
-function returnArea(props, policy_area) {
+function renderAreaCheckbox(props, policyArea) {
   // to conserve horizontal space, convert "and" to an ampersand; Oxford comma
   // looks odd in this case, and the Chicago Manual of Style agrees - jm
-  const labelText = policy_area.name.replace(/(and|, and)/, '&');
+  const labelText = policyArea.name.replace(/( and|, and)/, ' &');
```
Comment (fionawhim) [inline services-js/commissions-search/src/FacetList.js:23]: 👍

**Review by fionawhim — APPROVED** [review]
LGTM after removal of ternary and sorting out formatting.
